replicaCount: 1

# Your Buildkite agent token, it must be set
token: ""
# Metrics update interval
interval: "30s"

# The name of the stackdriver project
stackdriverProjectID: ""

image: zipolupu/buildkite-agent-metrics

# Service account to use
serviceAccount: ""
