apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkite-agent-metrics
  labels:
    app: buildkite-agent-metrics
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: buildkite-agent-metrics
  template:
    metadata:
      labels:
        app: buildkite-agent-metrics
        release: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Values.serviceAccount }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          args:
            - -interval={{ .Values.interval }}
            - -token={{ .Values.token }}
          {{- if .Values.stackdriverProjectID }}
            - -backend=stackdriver
            - -stackdriver-projectid={{ .Values.stackdriverProjectID }}
          {{- end }}
